#pragma module_prefix "io.dboost"
#pragma default_timeout 5000
module dboost_test
{

interface timer
{
  // returns -1 if some error happened, otherwise - timer id
  long add_timer(in long timeout_ms);

  //@@operation_timeout 1000
  void remove_timer(in long timer_id);
};

};
