interface timer_observer
{
  oneway void on_timeout();
};

interface timer
{
  /* returns -1 if some error happened */
  int add_timer(in int timeout_ms, in timer_observer observer);
  void remove_timer(in timer_observer observer);
};

