module dboost_test
{

struct date
{
  short year;
  short month;
  short day;
};

struct person
{
  string family_name;
  string name;
  date   birth_date;  
};

exception id_not_found {};

typedef sequence<person> Persons; 

interface database
{

  long add_person(in person p);
  person find_person_by_id(in long id) raises (id_not_found);
  void find_by_family(in string fn, out Persons k);
};

};
